Hello rails back-end
Loltolo-Lesapiti/-hello-rails-back-end pull request #1
Opened 2023-04-08 21:18 UTC by Loltolo-Lesapiti

This project;

- Creates a new Rails API app.
- Initialize it with Git.
- Sets Postgres database.
- Create a table for storing your messages and create 5 different greetings.
- Create an API endpoint that selects a random greeting from the table.

Link to front-end: https://github.com/Loltolo-Lesapiti/hello-react-front-end

2023-04-08 21:58 UTC, m05e5 requested changes
Hi @Loltolo-Lesapiti  , 

Good job so far. !
There are some issues that you still need to work on to go to the next project but you are almost there!
![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Highlights

- Professional readme file
- No linters error
- Good PR description

## Required Changes ♻️
* You really did a great job but there are some features you need to improve

- [ ] In your FE you are using `http://localhost:3000/api/v1/messages` as the route for the greeting meanwhile in the Backend you are passing the greeting route as the root. please kindly fix it
- [ ] Please see the comments bellow



_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-08 21:58 UTC, m05e5 commented on config/routes.rb
> +end
- [ ] It appears that you have a syntax error leading to an API error. In your controllers, you have MessagesController with index. So, the route is supposed to be `messages#index`

2023-04-11 04:49 UTC, Omar-Muhamad reviewed
# Invalid ❌

Hi @, 

#### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

#### Your Code Review Request is marked as invalid for this reason:

- [ ] Kindly check this [message](https://github.com/Loltolo-Lesapiti/hello-react-front-end/pull/1#pullrequestreview-1378442410) in the front-end PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2023-04-12 06:34 UTC, addod19 commented
### Hi @Loltolo-Lesapiti, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that IS INVALID because of this [reason](https://github.com/Loltolo-Lesapiti/hello-react-front-end/pull/1) in the frontend PR

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-12 07:46 UTC, TedLivist commented
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @Loltolo-Lesapiti,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Your frontend project has been marked as invalid for [the reasons listed here](https://github.com/Loltolo-Lesapiti/hello-react-front-end/pull/1#pullrequestreview-1380720055). Kindly resolve those documentation issues.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-12 10:00 UTC, Qoosim reviewed
#  *Status: Invalid Request* :red_circle: 

Hi @Loltolo-Lesapiti, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![](https://user-images.githubusercontent.com/97100091/194103659-a0270409-def7-4972-b884-9f7c141eb90a.gif)

## Invalid Code Review Request

You have submitted a project, that 

- [ ] has some missing headers such as Key Features and Future Features. Kindly add those headers and their appropriate information under each of them.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-12 12:21 UTC, Munsa1 requested changes
Hi @Loltolo-Lesapiti, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has incorrect git flow for both the front-end and the back-end. kindly request to merge `dev` branch into `main`
![image](https://user-images.githubusercontent.com/81932478/231455132-b77b69c6-a603-4f23-81e6-40a46a3f0a07.png)
![image](https://user-images.githubusercontent.com/81932478/231455249-b9fd2077-b60a-4602-8c3f-c80821e0450a.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-13 03:25 UTC, closed without merging